# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0002_auto_20170318_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('id', models.UUIDField(default=0, help_text='Unique 900# ID for this particular student', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('dr', 'Driscoll'), ('dw', 'Desert Willow'), ('t', 'Torres'), ('s', 'South'), ('w', 'West'), ('a', 'Alta'), ('o', 'Off Campus')], help_text='Current student residence', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='roominspectionform',
            name='title',
        ),
        migrations.AddField(
            model_name='roominspectionform',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rapp.Student'),
        ),
    ]
