# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 19:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0002_auto_20170501_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firealarm',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='programpacket',
            name='room_number',
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 1, 23, 40, 37, 992795, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roomentryrequestform',
            name='room_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='roomentryrequestform',
            name='student_sig',
            field=models.BinaryField(verbose_name='Resident signature image'),
        ),
        migrations.AlterField(
            model_name='safetyinspectionviolation',
            name='room_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='safetyinspectionviolation',
            name='sig',
            field=models.BinaryField(verbose_name='Student signature'),
        ),
    ]
