# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0002_auto_20170420_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roominspectionform',
            name='author',
        ),
        migrations.RemoveField(
            model_name='roominspectionform',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='roominspectionform',
            name='student',
        ),
        migrations.DeleteModel(
            name='RoomInspectionForm',
        ),
    ]
