# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0003_auto_20170318_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominspectionform',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.PositiveIntegerField(default=0, help_text='Unique 900# ID for this particular student', primary_key=True, serialize=False, unique=True),
        ),
    ]
