# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 03:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0003_auto_20170420_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='RA',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='roomentryrequestform',
            name='author',
        ),
        migrations.RemoveField(
            model_name='roomentryrequestform',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='roomentryrequestform',
            name='student',
        ),
        migrations.DeleteModel(
            name='Resident',
        ),
        migrations.DeleteModel(
            name='RoomEntryRequestForm',
        ),
    ]
