# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 01:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0004_auto_20170501_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 2, 5, 1, 19, 986881, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='programpacket',
            name='sig_date',
            field=models.DateField(blank=True, null=True, verbose_name='Signed date'),
        ),
    ]
