# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0004_auto_20170420_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('id', models.PositiveIntegerField(default=0, help_text='Unique 900# ID for this particular student', primary_key=True, serialize=False, unique=True)),
                ('student_email', models.EmailField(max_length=100)),
                ('emergency_contact', models.CharField(max_length=40)),
                ('contact_relationship', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.PositiveIntegerField()),
                ('home_addr', models.TextField(max_length=100)),
                ('car_plate', models.CharField(max_length=20)),
                ('car_info', models.TextField(help_text='Make/model/description of car', max_length=100)),
                ('room_number', models.CharField(max_length=10, null=True)),
                ('notes', models.TextField(max_length=1000)),
                ('RA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rapp.RA')),
                ('hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rapp.ResidenceHall')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomEntryRequestForm',
            fields=[
                ('room_number', models.TextField(max_length=10)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('student_sig', models.FileField(upload_to='')),
                ('ra_sig', models.BooleanField(default=False)),
                ('verification_method', models.TextField(max_length=40)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapp.RA')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapp.ResidenceHall')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rapp.Resident')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
