# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0005_resident_roomentryrequestform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ra',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='first_name',
        ),
    ]
