# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0005_student_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('dr', 'Driscoll'), ('dw', 'Desert Willow'), ('t', 'Torres'), ('s', 'South'), ('w', 'West'), ('a', 'Alta'), ('b', 'Baca'), ('o', 'Off Campus')], help_text='Current student residence', max_length=2),
        ),
    ]
