# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0006_auto_20170320_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='RA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.CharField(max_length=100)),
                ('emergency_contact', models.CharField(max_length=40)),
                ('contact_relationship', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.PositiveIntegerField(max_length=10)),
                ('home_addr', models.TextField(max_length=100)),
                ('car_plate', models.CharField(max_length=20)),
                ('car_info', models.TextField(help_text='Make/model/description of car', max_length=100)),
                ('student_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rapp.Student')),
            ],
        ),
    ]
