# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0006_auto_20170420_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='ra',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resident',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
