# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0007_auto_20170420_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ra',
            name='car_info',
            field=models.TextField(blank=True, default='none given', help_text='Make/model/description of car', max_length=100),
        ),
        migrations.AlterField(
            model_name='ra',
            name='car_plate',
            field=models.CharField(blank=True, default='none given', max_length=20),
        ),
        migrations.AlterField(
            model_name='ra',
            name='contact_relationship',
            field=models.CharField(blank=True, default='none given', max_length=100),
        ),
        migrations.AlterField(
            model_name='ra',
            name='emergency_contact',
            field=models.CharField(blank=True, default='none given', max_length=40),
        ),
        migrations.AlterField(
            model_name='ra',
            name='emergency_contact_phone',
            field=models.PositiveIntegerField(blank=True, default='none given'),
        ),
        migrations.AlterField(
            model_name='ra',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ra',
            name='home_addr',
            field=models.TextField(blank=True, default='none given', max_length=100),
        ),
        migrations.AlterField(
            model_name='ra',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ra',
            name='student_email',
            field=models.EmailField(default='lattaeo@gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='residencehall',
            name='id',
            field=models.PositiveIntegerField(default=0, help_text='Just an ID #', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='car_info',
            field=models.TextField(blank=True, default='none given', help_text='Make/model/description of car', max_length=100),
        ),
        migrations.AlterField(
            model_name='resident',
            name='car_plate',
            field=models.CharField(blank=True, default='none given', max_length=20),
        ),
        migrations.AlterField(
            model_name='resident',
            name='contact_relationship',
            field=models.CharField(blank=True, default='none given', max_length=100),
        ),
        migrations.AlterField(
            model_name='resident',
            name='emergency_contact',
            field=models.CharField(blank=True, default='none given', max_length=40),
        ),
        migrations.AlterField(
            model_name='resident',
            name='emergency_contact_phone',
            field=models.PositiveIntegerField(blank=True, default='none given'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resident',
            name='home_addr',
            field=models.TextField(blank=True, default='none given', max_length=100),
        ),
        migrations.AlterField(
            model_name='resident',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resident',
            name='notes',
            field=models.TextField(blank=True, default='No notes here!', max_length=1000),
        ),
        migrations.AlterField(
            model_name='resident',
            name='student_email',
            field=models.EmailField(default='lattaeo@gmail.com', max_length=100),
        ),
    ]
