# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0007_ra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ra',
            name='emergency_contact_phone',
            field=models.PositiveIntegerField(),
        ),
    ]
