# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0008_auto_20170320_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominspectionform',
            name='verification_method',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='roominspectionform',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapp.RA'),
        ),
    ]
