# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 06:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rapp', '0009_auto_20170321_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidenceHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rlc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='roominspectionform',
            name='verification_method',
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rapp.ResidenceHall'),
        ),
        migrations.AddField(
            model_name='ra',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rapp.ResidenceHall'),
        ),
    ]
