# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0010_auto_20170322_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencehall',
            name='id',
            field=models.PositiveIntegerField(default=0, help_text='Unique 900# ID for this particular student', primary_key=True, serialize=False, unique=True),
        ),
    ]
